Package updates and fixes. New buildscripts.

diff --git a/patches/sane-backends-fixes.patch b/patches/sane-backends-fixes.patch
--- a/patches/sane-backends-fixes.patch
+++ b/patches/sane-backends-fixes.patch
@@ -1,88 +1,62 @@
-diff -Naur a/backend/kodakaio.c b/backend/kodakaio.c
---- a/backend/kodakaio.c	2013-08-25 23:22:58.000000000 +0200
-+++ b/backend/kodakaio.c	2014-11-22 15:17:52.828328189 +0100
-@@ -127,7 +127,7 @@
- 
- #define KODAKAIO_VERSION	02
- #define KODAKAIO_REVISION	4
--#define KODAKAIO_BUILD		6
-+#define KODAKAIO_BUILD		7
- 
- /* for usb (but also used for net though it's not required). */
- #define MAX_BLOCK_SIZE		32768
-@@ -2184,6 +2184,7 @@
-     AvahiLookupResultFlags flags,
-     AVAHI_GCC_UNUSED void* userdata) {
- 
-+	AvahiStringList *vid_pair_list = NULL, *pid_pair_list = NULL;
- 	char *pidkey, *pidvalue;
- 	char *vidkey, *vidvalue;
- 	size_t valuesize;
-@@ -2204,20 +2205,40 @@
-             avahi_address_snprint(a, sizeof(a), address);
- 
- /* Output short for Kodak ESP */
--	DBG(min(10,DBG_AUTO), "%s:%u  %s  ", a,port,host_name);
--	avahi_string_list_get_pair(avahi_string_list_find(txt, "vid"), 
--		&vidkey, &vidvalue, &valuesize);
--	DBG(min(10,DBG_AUTO), "%s=%s  ", vidkey, vidvalue);
--	avahi_string_list_get_pair(avahi_string_list_find(txt, "pid"), 
--		&pidkey, &pidvalue, &valuesize);
--	DBG(min(10,DBG_AUTO), "%s=%s\n", pidkey, pidvalue);
-+	DBG(min(10,DBG_AUTO), "%s:%u  %s\n", a,port,host_name);
- 
-+	vid_pair_list = avahi_string_list_find(txt, "vid");
-+	if(vid_pair_list != NULL) {
-+		avahi_string_list_get_pair(vid_pair_list, &vidkey, &vidvalue, &valuesize);
-+		DBG(min(10,DBG_AUTO), "%s=%s  ", vidkey, vidvalue);
-+	}
-+	else	DBG(min(10,DBG_AUTO), "failed to find key vid\n");
-+
-+	pid_pair_list = avahi_string_list_find(txt, "pid");
-+	if(pid_pair_list != NULL) {
-+		avahi_string_list_get_pair(pid_pair_list, &pidkey, &pidvalue, &valuesize);
-+		DBG(min(10,DBG_AUTO), "%s=%s\n", pidkey, pidvalue);
-+	}
-+	else	DBG(min(10,DBG_AUTO), "failed to find key pid\n");
-+
-+	if(pid_pair_list != NULL && vid_pair_list != NULL) {
- 		ProcessAvahiDevice(name, vidvalue, pidvalue, a);
--	avahi_free(vidkey); avahi_free(vidvalue);
--	avahi_free(pidkey); avahi_free(pidvalue);
-+	}
-+	else DBG(min(10,DBG_AUTO), "didn't call ProcessAvahiDevice\n");
-+
-+	if(vid_pair_list != NULL) {
-+		avahi_free(vidkey); 
-+		avahi_free(vidvalue);
-+		DBG(min(15,DBG_AUTO), "vidkey and vidvalue freed\n");
-+	}
-+	if(pid_pair_list != NULL) {
-+		avahi_free(pidkey); 
-+		avahi_free(pidvalue);
-+		DBG(min(15,DBG_AUTO), "pidkey and pidvalue freed\n");
-+	}
-         }
-     }
--
-+    DBG(min(10,DBG_AUTO), "ending resolve_callback\n");
-     avahi_service_resolver_free(r);
- }
- 
-diff -Naur a/doc/descriptions/kodakaio.desc b/doc/descriptions/kodakaio.desc
---- a/doc/descriptions/kodakaio.desc	2013-09-18 02:43:00.000000000 +0200
-+++ b/doc/descriptions/kodakaio.desc	2014-11-22 15:17:52.828328189 +0100
-@@ -1,6 +1,6 @@
- :backend "kodakaio"
- :url "http://sourceforge.net/projects/cupsdriverkodak/" 
--:version "2.4.6"
-+:version "2.4.7"
- :manpage "sane-kodakaio"
- :comment "Backend for Kodak AiO ESP and Hero printers. Also possibly Advent AWL10"
- :devicetype :scanner
-diff -Naur a/sanei/sanei_tcp.c b/sanei/sanei_tcp.c
+--- a/configure	2015-10-04 15:18:39.000000000 +0200
++++ b/configure	2015-10-07 15:58:14.918139294 +0200
+@@ -9818,12 +9818,12 @@
+     pkg_cv_SYSTEMD_CFLAGS="$SYSTEMD_CFLAGS"
+  elif test -n "$PKG_CONFIG"; then
+     if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libsystemd-daemon\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "libsystemd-daemon") 2>&5
++    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libsystemd\""; } >&5
++  ($PKG_CONFIG --exists --print-errors "libsystemd") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   test $ac_status = 0; }; then
+-  pkg_cv_SYSTEMD_CFLAGS=`$PKG_CONFIG --cflags "libsystemd-daemon" 2>/dev/null`
++  pkg_cv_SYSTEMD_CFLAGS=`$PKG_CONFIG --cflags "libsystemd" 2>/dev/null`
+ 		      test "x$?" != "x0" && pkg_failed=yes
+ else
+   pkg_failed=yes
+@@ -9835,12 +9835,12 @@
+     pkg_cv_SYSTEMD_LIBS="$SYSTEMD_LIBS"
+  elif test -n "$PKG_CONFIG"; then
+     if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libsystemd-daemon\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "libsystemd-daemon") 2>&5
++    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libsystemd\""; } >&5
++  ($PKG_CONFIG --exists --print-errors "libsystemd") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   test $ac_status = 0; }; then
+-  pkg_cv_SYSTEMD_LIBS=`$PKG_CONFIG --libs "libsystemd-daemon" 2>/dev/null`
++  pkg_cv_SYSTEMD_LIBS=`$PKG_CONFIG --libs "libsystemd" 2>/dev/null`
+ 		      test "x$?" != "x0" && pkg_failed=yes
+ else
+   pkg_failed=yes
+@@ -9861,9 +9861,9 @@
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        SYSTEMD_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "libsystemd-daemon" 2>&1`
++	        SYSTEMD_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "libsystemd" 2>&1`
+         else
+-	        SYSTEMD_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "libsystemd-daemon" 2>&1`
++	        SYSTEMD_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "libsystemd" 2>&1`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$SYSTEMD_PKG_ERRORS" >&5
+--- a/configure.in	2015-10-03 04:00:34.000000000 +0200
++++ b/configure.in	2015-10-07 15:58:14.920139344 +0200
+@@ -368,7 +368,7 @@
+ if test "x$with_systemd" != xno ; then
+   PKG_CHECK_MODULES(SYSTEMD, [libsystemd], have_systemd=yes, have_systemd=no)
+   if test "x$have_systemd" = xno; then
+-    PKG_CHECK_MODULES(SYSTEMD, [libsystemd-daemon], have_systemd=yes, have_systemd=no)
++    PKG_CHECK_MODULES(SYSTEMD, [libsystemd], have_systemd=yes, have_systemd=no)
+   fi
+   if test "x$have_systemd" = xyes; then
+     AC_DEFINE(HAVE_SYSTEMD, 1, [Is /usr/include/systemd/sd-daemon.h available?])
 --- a/sanei/sanei_tcp.c	2013-08-26 03:01:38.000000000 +0200
-+++ b/sanei/sanei_tcp.c	2014-11-22 15:18:06.261550152 +0100
++++ b/sanei/sanei_tcp.c	2015-10-07 15:55:35.024133568 +0200
 @@ -45,6 +45,7 @@
  #include <unistd.h>
  #include <stdlib.h>
